### ISSUE TITLE
fail to open sculptor on 1.0.0

### ISSUE THREAD

**Issue by mostbill** [jtschindler/sculptor#1]
Hi JT,

I create a new environment to try the 1.0.0, but failed to open on "run_sculptor", wondering if this happen to you also? See below for the log:

> (sculptor-env-1.0.0) xie@lnx-d-0087:~/WORKSPACE/software/sculptor-1.0.0$ run_sculptor
> Traceback (most recent call last):
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/bin/run_sculptor", line 4, in <module>
>     __import__('pkg_resources').run_script('sculptor==1.0.0', 'run_sculptor')
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 662, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1466, in run_script
>     exec(script_code, namespace, namespace)
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/sculptor-1.0.0-py3.10.egg/EGG-INFO/scripts/run_sculptor", line 8, in <module>
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/sculptor-1.0.0-py3.10.egg/sculptor/specfitgui.py", line 13, in <module>
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/sculptor-1.0.0-py3.10.egg/sculptor/specfit.py", line 24, in <module>
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/sculptor-1.0.0-py3.10.egg/sculptor/specmodel.py", line 33, in <module>
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/sculptor-1.0.0-py3.10.egg/sculptor/masksmodels.py", line 260, in <module>
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1141, in resource_filename
>     return get_provider(package_or_requirement).get_resource_filename(
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1750, in get_resource_filename
>     return self._extract_resource(manager, zip_path)
>   File "/home/xie/anaconda3/envs/sculptor-env-1.0.0/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1772, in _extract_resource
>     timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
> KeyError: 'sculptor/../sculptor_extensions'

**Comment by unclellama** [comment]
Hi, I am also getting this issue with 1.0.0, on a fresh conda environment installed using the supplied yaml file. An earlier version worked for me! (unfortunately I reinstalled my OS since then...)

**Comment by jtschindler** [comment]
Hi, 
I apologize for the huge delay in answering to this issue. I have just updated the installation procedure for Sculptor, which now uses a setup.cfg in addition to the setup.py. 

Also the list of requirements and the environment.yml file are updated. Please follow the documentation with the new installation instructions in order to install Sculptor with python >=3.9. 

If you still encounter any issues, please let me know.
